# Generated by Django 6.0.3 on 2026-03-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='条码内容')),
                ('scan_time', models.DateTimeField(auto_now_add=True, verbose_name='扫描时间')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '条码记录',
                'verbose_name_plural': '条码记录',
                'db_table': 'barcode_record',
                'ordering': ['-scan_time'],
            },
        ),
    ]
