# Generated by Django 6.0.3 on 2026-04-21 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InverterParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product_code', models.CharField(max_length=50, verbose_name='产品编码')),
                ('input_voltage', models.CharField(blank=True, max_length=20, verbose_name='输入电压')),
                ('output_voltage', models.CharField(blank=True, max_length=20, verbose_name='输出电压')),
                ('input_current', models.CharField(blank=True, max_length=20, verbose_name='输入电流')),
                ('output_current', models.CharField(blank=True, max_length=20, verbose_name='输出电流')),
                ('power', models.CharField(blank=True, max_length=20, verbose_name='功率')),
                ('frequency_range', models.CharField(blank=True, max_length=50, verbose_name='频率范围')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.factory', verbose_name='所属工厂')),
            ],
            options={
                'verbose_name': '变频器参数',
                'verbose_name_plural': '变频器参数',
                'db_table': 'inverter_parameters',
            },
        ),
        migrations.CreateModel(
            name='MeterParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('product_code', models.CharField(max_length=50, verbose_name='产品编码')),
                ('voltage', models.CharField(blank=True, max_length=20, verbose_name='电压')),
                ('current', models.CharField(blank=True, max_length=20, verbose_name='电流')),
                ('power', models.CharField(blank=True, max_length=20, verbose_name='功率')),
                ('frequency', models.CharField(blank=True, max_length=20, verbose_name='频率')),
                ('accuracy', models.CharField(blank=True, max_length=20, verbose_name='精度')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.factory', verbose_name='所属工厂')),
            ],
            options={
                'verbose_name': '电表参数',
                'verbose_name_plural': '电表参数',
                'db_table': 'meter_parameters',
            },
        ),
    ]
