# Generated by Django 6.0.3 on 2026-04-21 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('equipment_code', models.CharField(max_length=50, unique=True, verbose_name='设备编码')),
                ('equipment_name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('type', models.CharField(max_length=50, verbose_name='设备类型')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='设备型号')),
                ('specification', models.CharField(blank=True, max_length=255, verbose_name='设备规格')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='制造商')),
                ('supplier', models.CharField(blank=True, max_length=100, verbose_name='供应商')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='状态')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='位置')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购买日期')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='安装日期')),
                ('warranty_end_date', models.DateField(blank=True, null=True, verbose_name='质保结束日期')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.factory', verbose_name='所属工厂')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='EquipmentFault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('fault_code', models.CharField(max_length=50, verbose_name='故障编码')),
                ('fault_description', models.TextField(verbose_name='故障描述')),
                ('fault_time', models.DateTimeField(verbose_name='故障发生时间')),
                ('fault_level', models.CharField(max_length=20, verbose_name='故障级别')),
                ('status', models.CharField(max_length=20, verbose_name='状态')),
                ('repair_content', models.TextField(blank=True, verbose_name='维修内容')),
                ('repair_time', models.DateTimeField(blank=True, null=True, verbose_name='维修时间')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faults', to='equipment.equipment', verbose_name='设备')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.factory', verbose_name='所属工厂')),
                ('repair_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repaired_faults', to='core.employee', verbose_name='维修人员')),
            ],
            options={
                'verbose_name': '故障记录',
                'verbose_name_plural': '故障记录',
                'db_table': 'equipment_faults',
            },
        ),
        migrations.CreateModel(
            name='EquipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(max_length=20, verbose_name='状态')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='状态描述')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_records', to='equipment.equipment', verbose_name='设备')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.factory', verbose_name='所属工厂')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_status_changes', to='core.user', verbose_name='操作人')),
            ],
            options={
                'verbose_name': '设备状态',
                'verbose_name_plural': '设备状态',
                'db_table': 'equipment_status',
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('plan_code', models.CharField(max_length=50, unique=True, verbose_name='计划编码')),
                ('plan_name', models.CharField(max_length=100, verbose_name='计划名称')),
                ('maintenance_type', models.CharField(max_length=50, verbose_name='维护类型')),
                ('scheduled_date', models.DateField(verbose_name='计划维护日期')),
                ('estimated_duration', models.PositiveIntegerField(verbose_name='预计维护时长(小时)')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='状态')),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_plans', to='core.employee', verbose_name='指派人员')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to='equipment.equipment', verbose_name='设备')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.factory', verbose_name='所属工厂')),
            ],
            options={
                'verbose_name': '维护计划',
                'verbose_name_plural': '维护计划',
                'db_table': 'maintenance_plans',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('maintenance_type', models.CharField(max_length=50, verbose_name='维护类型')),
                ('maintenance_date', models.DateField(verbose_name='维护日期')),
                ('duration', models.PositiveIntegerField(verbose_name='维护时长(小时)')),
                ('maintenance_content', models.TextField(verbose_name='维护内容')),
                ('maintenance_result', models.CharField(max_length=20, verbose_name='维护结果')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='equipment.equipment', verbose_name='设备')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.factory', verbose_name='所属工厂')),
                ('maintenance_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintained_records', to='core.employee', verbose_name='维护人员')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='equipment.maintenanceplan', verbose_name='维护计划')),
            ],
            options={
                'verbose_name': '维护记录',
                'verbose_name_plural': '维护记录',
                'db_table': 'maintenance_records',
            },
        ),
    ]
