# Generated by Django 6.0.3 on 2026-03-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='departments',
            field=models.ManyToManyField(blank=True, to='department.department', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='status',
            field=models.IntegerField(null=True, verbose_name='帐号状态（1正常 0停用）'),
        ),
    ]
