# Generated by Django 6.0.3 on 2026-03-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefectRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='日期')),
                ('product', models.CharField(max_length=100, verbose_name='产品')),
                ('report_qty', models.IntegerField(verbose_name='报工数量')),
                ('good_qty', models.IntegerField(verbose_name='良品数')),
                ('bad_qty', models.IntegerField(verbose_name='不良品数')),
            ],
            options={
                'verbose_name': '不良记录',
                'verbose_name_plural': '不良记录',
                'db_table': 'screen_defect_record',
            },
        ),
        migrations.CreateModel(
            name='DefectTypeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='不良品项')),
                ('value', models.IntegerField(verbose_name='数量')),
            ],
            options={
                'verbose_name': '不良品类型统计',
                'verbose_name_plural': '不良品类型统计',
                'db_table': 'screen_defect_type_stat',
            },
        ),
        migrations.CreateModel(
            name='EmployeePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50, verbose_name='员工姓名')),
                ('score', models.IntegerField(verbose_name='绩效分数')),
            ],
            options={
                'verbose_name': '员工绩效',
                'verbose_name_plural': '员工绩效',
                'db_table': 'screen_employee_performance',
            },
        ),
        migrations.CreateModel(
            name='ProcessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=50, verbose_name='工序名称')),
                ('plan_qty', models.IntegerField(verbose_name='计划数量')),
            ],
            options={
                'verbose_name': '工序计划',
                'verbose_name_plural': '工序计划',
                'db_table': 'screen_process_plan',
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, verbose_name='状态')),
            ],
            options={
                'verbose_name': '销售订单',
                'verbose_name_plural': '销售订单',
                'db_table': 'screen_sales_order',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, verbose_name='工单编号')),
                ('status', models.CharField(max_length=20, verbose_name='状态')),
                ('product_code', models.CharField(max_length=50, verbose_name='产品编号')),
                ('product_name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('spec', models.CharField(max_length=50, verbose_name='产品规格')),
                ('plan_qty', models.IntegerField(verbose_name='计划数量')),
                ('actual_qty', models.IntegerField(verbose_name='实际数量')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'db_table': 'screen_work_order',
            },
        ),
    ]
