# Generated by Django 6.0.3 on 2026-04-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysmenu',
            name='component',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='组件路径'),
        ),
        migrations.AlterField(
            model_name='sysmenu',
            name='create_time',
            field=models.DateField(blank=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='sysmenu',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='菜单图标'),
        ),
        migrations.AlterField(
            model_name='sysmenu',
            name='menu_type',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='菜单类型（M目录 C菜单 F按钮）'),
        ),
        migrations.AlterField(
            model_name='sysmenu',
            name='order_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='显示顺序'),
        ),
        migrations.AlterField(
            model_name='sysmenu',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='父菜单ID'),
        ),
        migrations.AlterField(
            model_name='sysmenu',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='路由地址'),
        ),
        migrations.AlterField(
            model_name='sysmenu',
            name='perms',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='权限标识'),
        ),
        migrations.AlterField(
            model_name='sysmenu',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='sysmenu',
            name='update_time',
            field=models.DateField(blank=True, null=True, verbose_name='更新时间'),
        ),
    ]
