# Generated by Django 6.0.3 on 2026-04-21 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('plan_code', models.CharField(max_length=50, unique=True, verbose_name='方案编码')),
                ('plan_name', models.CharField(max_length=100, verbose_name='方案名称')),
                ('inspection_type', models.CharField(choices=[('incoming', '来料检验'), ('process', '过程检验'), ('return', '退料检验'), ('shipping', '出货检验')], max_length=20, verbose_name='检验类型')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='状态')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.factory', verbose_name='所属工厂')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_plans', to='product.product', verbose_name='关联产品')),
            ],
            options={
                'verbose_name': '质检方案',
                'verbose_name_plural': '质检方案',
                'db_table': 'inspection_plans',
            },
        ),
        migrations.CreateModel(
            name='InspectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task_code', models.CharField(max_length=50, unique=True, verbose_name='任务编码')),
                ('inspection_type', models.CharField(choices=[('incoming', '来料检验'), ('process', '过程检验'), ('return', '退料检验'), ('shipping', '出货检验')], max_length=20, verbose_name='检验类型')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='批次号')),
                ('quantity', models.PositiveIntegerField(verbose_name='检验数量')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='任务状态')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='core.employee', verbose_name='指派人员')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.factory', verbose_name='所属工厂')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='quality.inspectionplan', verbose_name='质检方案')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_tasks', to='product.product', verbose_name='检验产品')),
            ],
            options={
                'verbose_name': '质检任务',
                'verbose_name_plural': '质检任务',
                'db_table': 'inspection_tasks',
            },
        ),
    ]
