# Generated by Django 6.0.3 on 2026-04-21 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('product', '0001_initial'),
        ('production', '0001_initial'),
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('material_code', models.CharField(blank=True, max_length=50, verbose_name='物料编码')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='批次号')),
                ('inspection_result', models.CharField(blank=True, max_length=20, verbose_name='检验结果')),
                ('inspection_time', models.DateTimeField(blank=True, null=True, verbose_name='检验时间')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.factory', verbose_name='所属工厂')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_inspections', to='core.employee', verbose_name='检验员')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.customer', verbose_name='供应商')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_inspections', to='quality.inspectiontask', verbose_name='待检任务')),
            ],
            options={
                'verbose_name': '来料检验',
                'verbose_name_plural': '来料检验',
                'db_table': 'incoming_inspections',
            },
        ),
        migrations.CreateModel(
            name='ProcessInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='批次号')),
                ('inspection_result', models.CharField(blank=True, max_length=20, verbose_name='检验结果')),
                ('inspection_time', models.DateTimeField(blank=True, null=True, verbose_name='检验时间')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.factory', verbose_name='所属工厂')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_inspections', to='core.employee', verbose_name='检验员')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.process', verbose_name='工序')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_inspections', to='quality.inspectiontask', verbose_name='待检任务')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_inspections', to='production.workorder', verbose_name='工单')),
            ],
            options={
                'verbose_name': '过程检验',
                'verbose_name_plural': '过程检验',
                'db_table': 'process_inspections',
            },
        ),
        migrations.CreateModel(
            name='ReturnInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('material_code', models.CharField(blank=True, max_length=50, verbose_name='物料编码')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='批次号')),
                ('return_reason', models.CharField(blank=True, max_length=255, verbose_name='退料原因')),
                ('inspection_result', models.CharField(blank=True, max_length=20, verbose_name='检验结果')),
                ('inspection_time', models.DateTimeField(blank=True, null=True, verbose_name='检验时间')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.factory', verbose_name='所属工厂')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_inspections', to='core.employee', verbose_name='检验员')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_inspections', to='quality.inspectiontask', verbose_name='待检任务')),
            ],
            options={
                'verbose_name': '退料检验',
                'verbose_name_plural': '退料检验',
                'db_table': 'return_inspections',
            },
        ),
        migrations.CreateModel(
            name='ShippingInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='批次号')),
                ('quantity', models.PositiveIntegerField(verbose_name='检验数量')),
                ('inspection_result', models.CharField(blank=True, max_length=20, verbose_name='检验结果')),
                ('inspection_time', models.DateTimeField(blank=True, null=True, verbose_name='检验时间')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.factory', verbose_name='所属工厂')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_inspections', to='core.employee', verbose_name='检验员')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_inspections', to='production.workorder', verbose_name='订单(工单)')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='产品')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_inspections', to='quality.inspectiontask', verbose_name='待检任务')),
            ],
            options={
                'verbose_name': '出货检验',
                'verbose_name_plural': '出货检验',
                'db_table': 'shipping_inspections',
            },
        ),
    ]
