# Generated by Django 6.0.3 on 2026-04-21 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('equipment', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('plan_name', models.CharField(max_length=100, verbose_name='计划名称')),
                ('product_type', models.CharField(max_length=50, verbose_name='产品类型')),
                ('quantity', models.PositiveIntegerField(verbose_name='计划数量')),
                ('start_barcode', models.CharField(blank=True, max_length=30, verbose_name='开始条码')),
                ('end_barcode', models.CharField(blank=True, max_length=30, verbose_name='结束条码')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('demand_date', models.DateField(verbose_name='需求日期')),
                ('source', models.IntegerField(choices=[(1, '客户订单'), (2, '库存备货')], verbose_name='来源')),
                ('status', models.CharField(default='draft', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to='core.user', verbose_name='创建人')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.customer', verbose_name='客户')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.factory', verbose_name='所属工厂')),
            ],
            options={
                'verbose_name': '生产计划',
                'verbose_name_plural': '生产计划',
                'db_table': 'production_plans',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='工单编号')),
                ('product_type', models.CharField(max_length=50, verbose_name='产品类型')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('start_barcode', models.CharField(blank=True, max_length=30, verbose_name='开始条码')),
                ('end_barcode', models.CharField(blank=True, max_length=30, verbose_name='结束条码')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='状态')),
                ('demand_date', models.DateField(blank=True, null=True, verbose_name='需求日期')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.factory', verbose_name='所属工厂')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='production.productionplan', verbose_name='生产计划')),
                ('process_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.processfile', verbose_name='工艺文件')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'db_table': 'work_orders',
            },
        ),
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product_code', models.CharField(max_length=50, verbose_name='产品编码')),
                ('parameter_name', models.CharField(max_length=100, verbose_name='参数名称')),
                ('parameter_value', models.CharField(max_length=100, verbose_name='参数值')),
                ('timestamp', models.DateTimeField(verbose_name='采集时间')),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.equipment', verbose_name='关联设备')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.factory', verbose_name='所属工厂')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user', verbose_name='操作人')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_data', to='production.workorder', verbose_name='关联工单')),
            ],
            options={
                'verbose_name': '生产数据',
                'verbose_name_plural': '生产数据',
                'db_table': 'production_data',
            },
        ),
        migrations.CreateModel(
            name='BarcodeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('barcode', models.CharField(max_length=50, verbose_name='条码')),
                ('barcode_type', models.IntegerField(choices=[(1, '厂内条码'), (2, '外壳条码'), (3, '主板条码'), (4, '电源板条码'), (5, '通讯板条码'), (6, '继电器板条码'), (7, '驱动板条码'), (8, '键盘板条码')], verbose_name='条码类型')),
                ('scanning_location', models.CharField(blank=True, max_length=100, verbose_name='扫描位置')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='扫描参数')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.factory', verbose_name='所属工厂')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.process', verbose_name='工序')),
                ('scanner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user', verbose_name='扫描人')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='production.workorder', verbose_name='工单')),
            ],
            options={
                'verbose_name': '条码扫描记录',
                'verbose_name_plural': '条码扫描记录',
                'db_table': 'barcode_scans',
            },
        ),
        migrations.CreateModel(
            name='BarcodeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('main_barcode', models.CharField(max_length=50, verbose_name='主条码')),
                ('main_barcode_type', models.IntegerField(choices=[(1, '厂内条码'), (2, '外壳条码'), (3, '主板条码'), (4, '电源板条码'), (5, '通讯板条码'), (6, '继电器板条码'), (7, '驱动板条码'), (8, '键盘板条码')], verbose_name='主条码类型')),
                ('sub_barcode', models.CharField(max_length=50, verbose_name='子条码')),
                ('sub_barcode_type', models.IntegerField(choices=[(1, '厂内条码'), (2, '外壳条码'), (3, '主板条码'), (4, '电源板条码'), (5, '通讯板条码'), (6, '继电器板条码'), (7, '驱动板条码'), (8, '键盘板条码')], verbose_name='子条码类型')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.factory', verbose_name='所属工厂')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='产品')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.workorder', verbose_name='工单')),
            ],
            options={
                'verbose_name': '条码关系',
                'verbose_name_plural': '条码关系',
                'db_table': 'barcode_relations',
            },
        ),
    ]
