# Generated by Django 6.0.3 on 2026-04-21 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('process_code', models.CharField(max_length=50, unique=True, verbose_name='工序编码')),
                ('process_name', models.CharField(max_length=100, verbose_name='工序名称')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.factory', verbose_name='所属工厂')),
            ],
            options={
                'verbose_name': '工序',
                'verbose_name_plural': '工序',
                'db_table': 'processes',
            },
        ),
        migrations.CreateModel(
            name='ProcessFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('file_code', models.CharField(max_length=50, unique=True)),
                ('file_name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('file_path', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='active', max_length=20)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.factory', verbose_name='所属工厂')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user', verbose_name='上传人')),
            ],
            options={
                'verbose_name': '工艺文件',
                'verbose_name_plural': '工艺文件',
                'db_table': 'process_files',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product_code', models.CharField(max_length=50, unique=True, verbose_name='产品编码')),
                ('product_name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('product_type', models.CharField(max_length=50, verbose_name='产品类型')),
                ('specification', models.CharField(blank=True, max_length=255)),
                ('product_image', models.ImageField(blank=True, upload_to='products/', verbose_name='产品图片')),
                ('status', models.CharField(default='active', max_length=20)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.factory', verbose_name='所属工厂')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sequence', models.PositiveIntegerField(verbose_name='工序顺序')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_processes', to='product.process', verbose_name='工序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_processes', to='product.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品工序',
                'verbose_name_plural': '产品工序',
                'db_table': 'product_processes',
                'constraints': [models.UniqueConstraint(fields=('product', 'sequence'), name='unique_product_sequence'), models.UniqueConstraint(fields=('product', 'process'), name='unique_product_process')],
            },
        ),
    ]
