# Generated by Django 6.0.3 on 2026-04-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_sysuser_departments_alter_sysuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='create_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
    ]
