# Generated by Django 6.0.3 on 2026-04-21 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('batch_number', models.CharField(max_length=100, verbose_name='批次号')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('production_date', models.DateField(verbose_name='生产日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有效期至')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='状态')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.factory', verbose_name='所属工厂')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '批次追溯',
                'verbose_name_plural': '批次追溯',
                'db_table': 'batch_tracking',
                'indexes': [models.Index(fields=['production_date'], name='batch_track_product_0a9ba7_idx')],
                'unique_together': {('batch_number', 'factory')},
            },
        ),
    ]
